### ISSUE TITLE
css属性设置为百分比时

### ISSUE THREAD

**Issue by zhanzizhen** [zhanzizhen/interview-knowledge#9]
## margin和padding

当margin和padding的值设置为百分比时，是指相对于最近的块级父元素width（非总宽度）的相应百分比的值，即使是margin-top、margin-bottom、padding-top、padding-bottom，设置为百分比时也是以最近块级父元素的width（非总宽度）为基准，而非height。

**Comment by zhanzizhen** [comment]
元素的width的百分比设置： 定义基于包含块（父元素）宽度的百分比宽度。 话虽如此，实际上无论怎么设置盒模型(box-sizing)的宽度，子元素都是基于父元素的内容（content）宽度并非width的实际大小。

**Comment by zhanzizhen** [comment]
## height

auto | 默认。浏览器会计算出实际的高度。
-- | --
length | 使用 px、cm 等单位定义高度。
% | 基于包含它的块级对象的百分比高度。
inherit | 规定应该从父元素继承 height 属性的值。

**Comment by zhanzizhen** [comment]
> ## margin和padding
> 当margin和padding的值设置为百分比时，是指相对于最近的块级父元素width（非总宽度）的相应百分比的值，即使是margin-top、margin-bottom、padding-top、padding-bottom，设置为百分比时也是以最近块级父元素的width（非总宽度）为基准，而非height。

**Comment by zhanzizhen** [comment]
利用padding百分比的特性，我们可以让盒子的宽度等于其高度

<div class='box'></div>
```css
 .box{
    width: 62%;
    display: block;
    margin: 0 auto 6px;
    padding-top: 62%;
    position: relative;
}
```

常用到的场景有很多，比如让图片始终保持1:1
<div class='box'><img src="xxx" /></div>
```css
.box>img{
width: 100%;
    height: 100%;
    position: absolute;
    left: 0;
    top: 0;
}
```
